# Generated by Django 6.1.2 on 2026-10-07 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Назва')),
                ('category', models.CharField(max_length=100, verbose_name='Категорія')),
                ('material', models.CharField(max_length=100, verbose_name='Матеріал')),
                ('brand', models.CharField(max_length=100, verbose_name='Бренд')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна')),
            ],
        ),
    ]
